### ISSUE TITLE
Implement batched off-thread HSA signal waiting

### ISSUE THREAD

**Issue by jpsamaroo** [JuliaGPU/AMDGPU.jl#128]
Polling signals is generally a bad idea when one has many, many signals with long delays being waited on. While #84 will help with that, it would be more ideal if an interrupt-based mechanism could be used. I think we could use one of the libuv threads (or even spawn off our own thread) that will batch up all outstanding signals to be waited on by `HSA.signal_wait_group_any_*`. We would keep a single control signal available to interrupt the waiter when new signals need to be added, possibly after a small delay where polling is briefly used (to prevent excessive signal changes).

This will require that ROCR does not block our entire process while waiting; if this happens, we'll probably need to fix ROCR itself.

**Comment by pxl-th** [comment]
We no longer use HSA signals.
