### ISSUE TITLE
Use `Array{UInt8}(undef, len)` instead of `repeat(" ", len)`

### ISSUE THREAD

**Issue by vchuravy** [JuliaGPU/AMDGPU.jl#132]
Julia strings are defined to be immutable. So this is technically not valid

https://github.com/JuliaGPU/AMDGPU.jl/blob/43124078c1c5b6359967877d1f1dab0ba4acdf2b/src/agent.jl#L196

`String(buf)` makes a zero copy `String` from an `Array`

**Comment by jpsamaroo** [comment]
Oh dear...

**Comment by jpsamaroo** [comment]
@vchuravy I believe this is now fixed?

**Comment by jpsamaroo** [comment]
Fixed by #136
