### ISSUE TITLE
CUDA vs AMDGPU

### ISSUE THREAD

**Issue by Cvikli** [JuliaGPU/AMDGPU.jl#137]
Hey, 

I made some tests. AMDGPU looks really promising based on these test. I don't 100% measure the same, because we measure 200 more kernel call in case of CUDA. 

Initalization:
```
N=1<<25
a = randn(Float32, N)
b = randn(Float32, N)
;
```

**AMD GPU used: Vega 20 [Radeon VII] (gfx906)**
```
using AMDGPU

@time a_d = AMDGPU.ROCArray(a)  # 0.0206s
@time b_d = AMDGPU.ROCArray(b)  # 0.0192s
@time c_d = similar(a_d)  # 0.000353s

function vadd!(c, a, b)
  idx = (workgroupDim().x * (workgroupIdx().x-1)) + workitemIdx().x
	for i=1:200
  	c[idx] = a[idx] + b[idx]
	end
	nothing
end

@time wait(@roc groupsize=min(1024,length(c_d)) gridsize=length(c_d) vadd!(c_d, a_d, b_d))
@time wait(@roc groupsize=min(1024,length(c_d)) gridsize=length(c_d) vadd!(c_d, a_d, b_d))
@time wait(@roc groupsize=min(1024,length(c_d)) gridsize=length(c_d) vadd!(c_d, a_d, b_d))
@time wait(@roc groupsize=min(1024,length(c_d)) gridsize=length(c_d) vadd!(c_d, a_d, b_d))
```
Results:
```
# 0.828217 seconds (284.10 k allocations: 17.820 MiB)
# 0.043772 seconds (7.42 k allocations: 472.243 KiB, 17.31% compilation time)
# 0.045004 seconds (7.42 k allocations: 472.665 KiB, 15.12% compilation time)
# 0.043043 seconds (7.48 k allocations: 473.728 KiB, 19.39% compilation time)
```

**Nvidia GPU used: NVidia 1080Ti 11GB**
```
using CUDA

@time CUDA.@sync a_cu = CUDA.randn(Float32,N) # 0.021298 seconds (41 allocations: 1.141 KiB)
@time CUDA.@sync b_cu = CUDA.randn(Float32,N) # 0.001279 seconds (35 allocations: 1.031 KiB)
@time CUDA.@sync c_cu = CUDA.randn(Float32,N) # 0.001367 seconds (35 allocations: 1.031 KiB)

abstractadd!(c::AbstractArray, a::AbstractArray, b::AbstractArray) = for i=1:200 c .= b .+ a end

@time CUDA.@sync  abstractadd!(x_cu, y_cu)
@time CUDA.@sync  abstractadd!(x_cu, y_cu)
@time CUDA.@sync  abstractadd!(x_cu, y_cu)
@time CUDA.@sync  abstractadd!(x_cu, y_cu)
```
Results:
```
# 0.213468 seconds (3.01 k allocations: 81.406 KiB) Here there is some compilation speed but made a mistake and deleted those result but we don't check compilation atm...
# 0.213752 seconds (3.01 k allocations: 81.406 KiB)
# 0.216686 seconds (3.01 k allocations: 81.406 KiB)
# 0.219197 seconds (3.01 k allocations: 81.406 KiB)
```

### 5x speedup with AMD (As noted, we measured 200 kernel call too with CUDA.)
Would be really nice results if everything is all right! 

For me AMD looks great in these test. I don't know if it can reach the stable version like CUDA, and fitting into the ecosystem and be used everywhere where AbstractArray is used. 
If ROCArray could implement the same pattern like CUDA without any overhead it would be really big deal fog AMD.

**Comment by jpsamaroo** [comment]
Thanks for running these! What sizes of arrays did you use? I'm also slightly concerned that you're timing different implementations of the same algorithm; maybe try benchmarking the same implementation for both packages? AMDGPU also supports broadcast operations, btw.

> If ROCArray could implement the same pattern like CUDA without any overhead it would be really big deal fog AMD.

I think we can implement basically everything similarly to CUDA, since GPUArrays and KernelAbstractions support already exists and works at a basic level. It's just a matter of time and effort :slightly_smiling_face:

**Comment by Cvikli** [comment]
Sorry I missed some of the main details. 

I add the "N" size and a,b array now! 

I didn't know it support broadcast. Can you give an example on how would you change the `vadd!` function?

**Comment by Cvikli** [comment]
#I think we can implement basically everything similarly to CUDA, since GPUArrays and KernelAbstractions support already exists and works at a basic level. It's just a matter of time and effort slightly_smiling_face
This would be DAMN crazy! If this gets stable... wow!

**Comment by Cvikli** [comment]
> I think we can implement basically everything similarly to CUDA, since GPUArrays and KernelAbstractions support already exists and works at a basic level. It's just a matter of time and effort
This would be DAMN crazy! If this gets stable... wow!

**Comment by vchuravy** [comment]
You are benchmarking two very different things. In the CUDA case you are launching 200 individual kernels, whereas in the AMDGPU case you are launching 1 kernel doing 200 iterations.

**Comment by Cvikli** [comment]
Yes, you are right. The speed difference in this case isn't correct. I should try the broadcast version to measure the same then.

**Comment by Cvikli** [comment]
I recreated the test as @vchuravy asked:
```
function vadd!(c, a, b)
  idx = (workgroupDim().x * (workgroupIdx().x-1)) + workitemIdx().x
  c[idx] = a[idx] + b[idx]
	nothing
end
@time for i=1:200 wait(@roc groupsize=min(1024,length(c_d)) gridsize=length(c_d) vadd!(c_d, a_d, b_d)) end
```
Results:
```
  0.622263 seconds (30.96 k allocations: 1.308 MiB, 1.53% compilation time)
  0.619233 seconds (31.48 k allocations: 1.314 MiB, 1.49% compilation time)
  0.617594 seconds (31.51 k allocations: 1.317 MiB, 1.34% compilation time)
  0.608710 seconds (31.49 k allocations: 1.316 MiB, 1.11% compilation time)
```
This looks like these two are close to the same which still pretty good already! It is good to know there is **5x speed** opportunity with sparing the kernel calls, which can be even bigger when working on little chunks!
