### ISSUE TITLE
Problems on 4750U mobile APU

### ISSUE THREAD

**Issue by simeonschaub** [JuliaGPU/AMDGPU.jl#142]
As discussed on Slack a while back. I installed the packages `rock-dkms-bin`, `hsa-runtime-git` and `rocm` on Manjaro Linux and building AMDGPU.jl with `JULIA_AMDGPU_DISABLE_ARTIFACTS=1` seems to work fine, but as soon as I try any operations on ROCArrays, I get the following error: https://gist.github.com/simeonschaub/d1bcee2600f69e08e82a229da490ffc6.
```
julia> versioninfo()
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 7 PRO 4750U with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, znver2)
Environment:
  JULIA_NUM_THREADS = 8
```

**Comment by vchuravy** [comment]
Can you try again, on current master?

**Comment by simeonschaub** [comment]
What's the current state regarding artifacts? Are they fully functional like the CUDA ones nowadays, or do I still need to install the hsa/rocm runtime through the system package manager?

**Comment by vchuravy** [comment]
On Julia 1.6 the artifacts "should" just work.

**Comment by simeonschaub** [comment]
Hmm, doing `roc([1f0]) .+ roc([2f0])` does weird things to my screen but otherwise not a whole lot:

![PXL_20211031_040921573.jpg](https://user-images.githubusercontent.com/5220528/139567243-b98ed35e-c5f5-49b3-aa39-c0dcf41304f1.jpg)

Is this art? 😅

**Comment by jpsamaroo** [comment]
@simeonschaub it might be worth updating your kernel to something recent and trying out #187 on Julia 1.7. That would get you a reasonably up-to-date ROCm, which probably has better APU support.

**Comment by simeonschaub** [comment]
I don't know what wizardry you have done here, but it actually seems to be mostly working with a 5.15 kernel! :tada: Running the entire test suite, I believe there might still be a hang somewhere in the GPUArrays suite and if I try to cancel the process using `Ctrl+c`. I am currently trying to narrow that down a bit more. I also haven't tested all the external libs like rocBLAS yet.

**Comment by simeonschaub** [comment]
I think I spoke too soon. The GPUArrays test suite actually passed except for the one requiring rocRAND. So I think I just underestimated the runtime of these tests and the crash might have just been a matter of AMDGPU not handling interrupts gracefully. I will consider this issue to be fixed now, I'll open a new one if I encounter a crash or any other issues again.
