### ISSUE TITLE
ROCArray : LoadError: UndefRefError: access to undefined reference

### ISSUE THREAD

**Issue by alephpt** [JuliaGPU/AMDGPU.jl#153]
trying to initialize a ROCArray with a matrix, as you can do in CuArray, I get an undefined reference error. Assuming I was using the wrong type, I looked in the source and found `const ROCMatrix{T} = ROCArray{T,2}` - which also returns the same error.

the code that produced the error is simply `ucsteps = ROCArray(zeros(Int, (height, width)))`

The error for this was:
```
ERROR: LoadError: UndefRefError: access to undefined reference
Stacktrace:
  [1] getproperty
    @ ./Base.jl:33 [inlined]
  [2] getindex
    @ ./refvalue.jl:56 [inlined]
  [3] get_default_agent
    @ ~/.julia/packages/AMDGPU/t1BEF/src/agent.jl:114 [inlined]
  [4] #alloc#2
    @ ~/.julia/packages/AMDGPU/t1BEF/src/memory.jl:227 [inlined]
  [5] alloc
    @ ~/.julia/packages/AMDGPU/t1BEF/src/memory.jl:227 [inlined]
  [6] ROCArray
    @ ~/.julia/packages/AMDGPU/t1BEF/src/array.jl:108 [inlined]
  [7] ROCMatrix{Int64}(x::Matrix{Int64}, dims::Tuple{Int64, Int64})
    @ AMDGPU ~/.julia/packages/AMDGPU/t1BEF/src/array.jl:122
  [8] ROCArray
    @ ~/.julia/packages/AMDGPU/t1BEF/src/array.jl:149 [inlined]
  [9] ROCArray
    @ ~/.julia/packages/AMDGPU/t1BEF/src/array.jl:154 [inlined]
 [10] mandelplot()
    @ Main ~/repos/Julia/mandelbrot/mandelbrot.jl:60
 [11] top-level scope
    @ ~/repos/Julia/mandelbrot/mandelbrot.jl:87
in expression starting at /home/sister/repos/Julia/mandelbrot/mandelbrot.jl:87
```

I'm going to attempt to see if I can find any major differences in CuArray versus ROCArray that makes this unusable. Maybe there is an error in my code that I am missing.. definitely look forward to finding out what the solution to this problem is or if we can find a patch. 

Thanks

**Comment by jpsamaroo** [comment]
What probably happened is that the HSA runtime didn't get successfully initialized. Do you get any warnings when you do `using AMDGPU` the first time in a Julia session? If so, you need to do a `using Pkg; Pkg.build("AMDGPU")`. If it still gives you a warning, check `deps/build.log` for errors relating to the HSA runtime, HIP, or ld.lld.

I should probably modify `get_default_agent` to throw a more meaningful error in this case...

**Comment by alephpt** [comment]
have already done the above. 
not seeing a build.log though.

No errors at this point with AMDGPU other than having to initially install Julia from `yay julia-bin` and then following the steps you listed above.

**Comment by alephpt** [comment]
I am unsure why but I am getting `LoadError: MethodError: no method matching ROCArray(::Tuple{Int64, Int64})`

**Comment by jpsamaroo** [comment]
> Other than the above, I haven't seen any direct errors with AMDGPU, since re-installing Julia from yay julia-bin, and then following the steps you listed above.

It concerns me that you're using Julia from a distro package manager, but I suppose it might be okay. Did you check `AMDGPU/deps/build.log`? I'd appreciate if you could post the contents so I can be more helpful in debugging this.

> Via nteract and julia cli I am seeing an error stating that there is no method for ROCArray for some reason.

> I am unsure why but I am getting LoadError: MethodError: no method matching ROCArray(::Tuple{Int64, Int64})

We don't have a method for this; if you'd like to add one, I'd appreciate the contribution!

**Comment by alephpt** [comment]
Well, it looks like there are a few methods that could be implemented. I will definitely be glad to help and contribute to this in any way possible.

Also, I am not seeing a build.log ?

**Comment by alephpt** [comment]
it appears that there is a `ROCMatrix{Float64}(x::Matrix{Float64}, dims::Tuple{Int64, Int64})` function

**Comment by jpsamaroo** [comment]
> it appears that there is a ROCMatrix{Float64}(x::Matrix{Float64}, dims::Tuple{Int64, Int64}) function

Oh, if you want to allocate an array with those dimensions, do `ROCArray(undef, dims)` or `ROCArray(undef, dims...)`.

**Comment by jpsamaroo** [comment]
> Also, I am not seeing a build.log ?

It's easier to find if you `] dev AMDGPU`, and then build that version. Then it's usually in `~/.julia/dev/AMDGPU/deps/build.log`.

**Comment by alephpt** [comment]
> > it appears that there is a ROCMatrix{Float64}(x::Matrix{Float64}, dims::Tuple{Int64, Int64}) function
> 
> Oh, if you want to allocate an array with those dimensions, do `ROCArray(undef, dims)` or `ROCArray(undef, dims...)`.

the above code gave me - 
`LoadError: MethodError: no method matching ROCArray(::UndefInitializer, ::Tuple{Int64, Int64})`
`LoadError: MethodError: no method matching ROCArray(::UndefInitializer, ::Matrix{Float64})` or 
`LoadError: MethodError: no method matching ROCArray(::UndefInitializer, ::Int64)` depending on my input


I was not seeing a deps/build log until after I ran the dev AMDGPU which gave me
```
Activating environment at `~/.julia/dev/AMDGPU/Project.toml`
[ Info: Found useable ld.lld at /usr/bin/ld.lld
paths = String[]
Could not find library 'rocblas'.
Could not find library 'rocsparse'.
Could not find library 'rocalution'.
Could not find library 'rocfft'.
Could not find library 'rocrand'.
Could not find library 'MIOpen'.
```
I imagine this is probably a big part of my problem lol

I also happened to run `] test AMDGPU` and got the output below
`
Test Summary:                                                        | Pass  Error  Broken  Total
 AMDGPU                                                               |   23   1967       4     1994
`

Will be interesting to see the difference in results if these libraries are found.

I definitely appreciate your help!

**Comment by jpsamaroo** [comment]
Sorry, you need to specify the type: `ROCArray{Float32}(undef, (4,2))` works for me. Otherwise it's not known what the element type should be.

> I imagine this is probably a big part of my problem lol

This generally looks fine to me; those libraries are optional, and basically all the tests pass without them. What's in `deps/ext.jl`?

**Comment by alephpt** [comment]
```
# autogenerated file, do not edit
const hip_configured = true
const libhsaruntime_version = v"1.1.0"
const librocsparse = nothing
const libhsaruntime_path = "/home/sister/.julia/artifacts/8c409789c2ebf3ec6b5a4da6f13afaadfa3cb104/lib/libhsa-runtime64.so"
const libhip_path = "/home/sister/.julia/artifacts/c32760c7999f5a915318fa07773ec1729e3a9136/hip/lib/libamdhip64.so"
const librocfft = nothing
const librocrand = nothing
const librocblas = nothing
const device_libs_configured = true
const librocalution = nothing
const libmiopen = nothing
const device_libs_path = "/home/sister/.julia/artifacts/65242d8c88c23806807d43058cdac7ece85e9d4b/amdgcn/bitcode"
const hsa_configured = true
const device_libs_downloaded = false
const ld_lld_path = "/usr/bin/ld.lld"
```

**Comment by jpsamaroo** [comment]
Ok, then it's clear that your libraries are loading fine, but HSA doesn't detect any agents (GPU devices). Do you have `rocminfo` installed? If so, could you post the results of running it to a pastebin like https://paste.sr.ht (since the output can be pretty big)? It's possible that either your GPU/Linux kernel is misconfigured, or (probably more likely) the ROCR we ship can't detect your card because it's too old or too new.

**Comment by alephpt** [comment]
I'm running RX580

rocminfo
```
ROCk module is loaded
=====================
HSA System Attributes
=====================
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE
System Endianness:       LITTLE

==========
HSA Agents
==========
*******
Agent 1
*******
  Name:                    AMD Phenom(tm) II X4 955 Processor
  Uuid:                    CPU-XX
  Marketing Name:          AMD Phenom(tm) II X4 955 Processor
  Vendor Name:             CPU
  Feature:                 None specified
  Profile:                 FULL_PROFILE
  Float Round Mode:        NEAR
  Max Queue Number:        0(0x0)
  Queue Min Size:          0(0x0)
  Queue Max Size:          0(0x0)
  Queue Type:              MULTI
  Node:                    0
  Device Type:             CPU
  Cache Info:
    L1:                      65536(0x10000) KB
  Chip ID:                 0(0x0)
  Cacheline Size:          64(0x40)
  Max Clock Freq. (MHz):   3200
  BDFID:                   0
  Internal Node ID:        0
  Compute Unit:            4
  SIMDs per CU:            0
  Shader Engines:          0
  Shader Arrs. per Eng.:   0
  WatchPts on Addr. Ranges:1
  Features:                None
  Pool Info:
    Pool 1
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    16373396(0xf9d694) KB
      Allocatable:             TRUE
      Alloc Granule:           4KB
      Alloc Alignment:         4KB
      Accessible by all:       TRUE
    Pool 2
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED
      Size:                    16373396(0xf9d694) KB
      Allocatable:             TRUE
      Alloc Granule:           4KB
      Alloc Alignment:         4KB
      Accessible by all:       TRUE
  ISA Info:
    N/A
*** Done ***
```

**Comment by jpsamaroo** [comment]
And that's the issue: `rocminfo` (which uses HSA/ROCR) only detects your CPU, which we won't use in AMDGPU. This is because your GPU is "too old" (according to AMD) to be supported by ROCm, unfortunately. I had the same thing happen to me, and had to remove the RX480 that I had been happily using for CI about a year ago.

My advice to you is unfortunate: get a slightly newer GPU if you want to use AMDGPU (or anything that uses ROCm). I would recommend anything in the Vega lineup; I use two Vega 56s for CI, and they're plenty fast enough.

You can also try to petition AMD to add back support for Polaris cards, but there are already a lot of people complaining about it, and AMD hasn't changed course.

The other alternative that I don't personally have time to investigate is patching support back into modern ROCR for Polaris cards; I'm not sure how much code AMD ripped out when removing Polaris support, but it might be simple enough to add back in. If you want to take this on, post an initial PR patching the `hsa_rocr_jll` package to [Yggdrasil](https://github.com/JuliaPackaging/Yggdrasil) and ping me, and I'll be happy to review and try to assist.

Sorry to be the bearer of bad news, but I'm going to close this issue since it's not something I can easily fix.

**Comment by alephpt** [comment]
I definitely appreciate your time and support! I'll definitely look into possible solutions.

**Comment by alephpt** [comment]
According to ROCm documentation it is supported, so maybe there's something in my system configurations that aren't set up right.

If I come to a viable solution I will post an update.

Link: https://sep5.readthedocs.io/en/latest/Installation_Guide/Installation-Guide.html
