### ISSUE TITLE
`wavefrontsize64_{on|off}.bc` missing with `JULIA_AMDGPU_DISABLE_ARTIFACTS=true`

### ISSUE THREAD

**Issue by vchuravy** [JuliaGPU/AMDGPU.jl#172]

**Comment by jpsamaroo** [comment]
Yeah that's because the device libs we ship when it's `true` are old and don't have those. We should change that to search in `/opt/rocm*` for the bitcode files correctly.

**Comment by jpsamaroo** [comment]
Should hopefully be resolved by #180, which is going to simply disable the old ROCmDeviceLibsDownloader-provided bitcode files, and will instead load them from `/opt/rocm/amdgcn/bitcode` when artifacts are disabled.

**Comment by jpsamaroo** [comment]
Fixed by #180
