### ISSUE TITLE
Build fails on OSX

### ISSUE THREAD

**Issue by clive-g-brown** [JuliaGPU/AMDGPU.jl#19]
hope you complete this package -

as im sure you know - fails to compile on OSX.

Error: Error building `AMDGPUnative`: 
│ ERROR: LoadError: Your platform ("x86_64-apple-darwin18.6.0", parsed as "x86_64-apple-darwin14-gcc8-cxx03") is not supported by this package!
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] top-level scope at /Users/cbrown/.julia/packages/AMDGPUnative/gE2NQ/deps/build.jl:26
│  [3] include(::String) at ./client.jl:439
│  [4] top-level scope at none:5
│ in expression starting at /Users/cbrown/.julia/packages/AMDGPUnative/gE2NQ/deps/build.jl:22
└ @ Pkg.Operations /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Operations.jl:892

**Comment by jpsamaroo** [comment]
I don't think I'll be picking back up OpenCL support, unless someone adventurous wishes to do the work.
