### ISSUE TITLE
Move standard warnings of using AMDGPU on system without AMD GPU to @debug?

### ISSUE THREAD

**Issue by omlins** [JuliaGPU/AMDGPU.jl#199]
When using AMDGPU on system without AMD GPU the following warnings seem to occur always:
```julia
julia> using AMDGPU
[ Info: Precompiling AMDGPU [21141c5a-9bdb-4563-92ae-f87d6854732e]
┌ Warning: HSA runtime has not been built, runtime functionality will be unavailable.
│ Please run Pkg.build("AMDGPU") and reload AMDGPU.
│ Reason: Failed to initialize HSA runtime, status code: 4104
└ @ AMDGPU /scratch/snx3000tds/julia/omlins/daint-gpu/packages/AMDGPU/ZIg6T/src/AMDGPU.jl:186
┌ Warning: ld.lld was not found, compilation functionality will be unavailable.
│ Please run Pkg.build("AMDGPU") and reload AMDGPU.
│ Reason: unknown
└ @ AMDGPU /scratch/snx3000tds/julia/omlins/daint-gpu/packages/AMDGPU/ZIg6T/src/AMDGPU.jl:207
┌ Warning: HIP library has not been built, runtime functionality will be unavailable.
│ Please run Pkg.build("AMDGPU") and reload AMDGPU.
│ Reason: unknown
└ @ AMDGPU /scratch/snx3000tds/julia/omlins/daint-gpu/packages/AMDGPU/ZIg6T/src/AMDGPU.jl:217
┌ Warning: ROCm-Device-Libs were not found, device intrinsics will be unavailable.
│ Please run Pkg.build("AMDGPU") and reload AMDGPU.
│ Reason: unknown
└ @ AMDGPU /scratch/snx3000tds/julia/omlins/daint-gpu/packages/AMDGPU/ZIg6T/src/AMDGPU.jl:226
```
Would it make sense to show them only if the AMDGPU model is used in debug mode? This would align it with CUDA.jl which gives no warnings in standard mode when doing `using CUDA` on a system without a CUDA-capable GPU.

As for issue #198, this would be useful for conditional usage of AMDGPU,  as described in [this discourse post](https://discourse.julialang.org/t/how-to-add-cuda-as-optional-dependency/73077/7?u=samo) for CUDA.jl.

**Comment by jpsamaroo** [comment]
I'd be willing to delay these until the first time such functionality is used. @omlins do you feel comfortable writing a PR for this?

**Comment by jpsamaroo** [comment]
> Would it make sense to show them only if the AMDGPU model is used in debug mode?

With the ROCm artifacts not currently being very complete or up-to-date, I'd like to shy away from hiding this for now. In the future, when our artifacts are comprehensive, we can revisit this.

**Comment by omlins** [comment]
@jpsamaroo : would you have a suggestion for an easy and robust check if a AMD GPU card (hardware) is available on the system, in order to allow not to do `using AMDGPU` if no GPU is available at all? The problem in the current state is that a package that supports multiple hardware as AMD and NVIDIA GPU will always trigger these warnings, even if there is not even an AMDGPU available on a particular system.

**Comment by omlins** [comment]
...or an alternative could be an environement variable to force deactivate these warnings?

**Comment by vchuravy** [comment]
Yeah we should have:

```
using AMDGPU
AMDGPU.isfunctional() # or whatever CUDA ended up calling it
```
