### ISSUE TITLE
Add `unsafe_wrap` for AMDGPU

### ISSUE THREAD

**Issue by luraess** [JuliaGPU/AMDGPU.jl#203]
The `unsafe_wrap` functionality may be missing for AMDGPU.jl (for CUDA.jl analogy, see [here](https://github.com/JuliaGPU/CUDA.jl/blob/7de4c459f7cb4be552f18f220a72986de1a1aec3/src/array.jl#L180-L223))

**Comment by rejuvyesh** [comment]
Might be useful for https://github.com/pabloferz/DLPack.jl/issues/22 too.
