### ISSUE TITLE
Feature request: allow `hsa_amd_memory_copy_async` to pick a queue

### ISSUE THREAD

**Issue by luraess** [JuliaGPU/AMDGPU.jl#204]
This would expose similar API as CUDA.jl's `CUDA.Mem.unsafe_copy3d!`.

Suggestion from @jpsamaroo: write a memcopy kernel and put it directly in AMDGPU.jl exposing an argument to specify which queue to use.

**Comment by luraess** [comment]
@jpsamaroo #220 may close this?

**Comment by pxl-th** [comment]
We now support this with HIP version.
