### ISSUE TITLE
`hsa_executable_freeze` can hang during high GPU load

### ISSUE THREAD

**Issue by jpsamaroo** [JuliaGPU/AMDGPU.jl#208]
When the GPU is under high load and spinning on `AMDGPU.device_signal_wait`, `hsa_executable_freeze` can hang as it tries to synchronize with the GPU. We should switch to using an `InterruptSignal` (exposed via HSA) to ensure we don't effectively hang the GPU and impede timely forward progress.

**Comment by pxl-th** [comment]
We no longer use this. And with hip we perform device sync right before loading `hipModule`.
Although we can wrap it in alloc/retry if we ever encounter an issue with this.
