### ISSUE TITLE
Implement copy!()

### ISSUE THREAD

**Issue by torrance** [JuliaGPU/AMDGPU.jl#218]
Given two arrays, eg. `arr` and `arr_d`, ensure `copy!(arr_d, arr)` does the right thing. Currently it complains on scalar indexing.

This should also work for both device to host, and device to device copies too.

This is implemented in CUDA.jl.

**Comment by jpsamaroo** [comment]
This should already work: https://github.com/JuliaGPU/AMDGPU.jl/blob/bd8b4c400bd440c571beb33f9921be28323ce573/src/array.jl#L178-L214

Can you provide an MWE of where this doesn't work?

**Comment by torrance** [comment]
Those snippets are copyto!(), not copy!(), right?

**Comment by jpsamaroo** [comment]
What's the difference between `copy!` and `copyto!`? The docstring makes it sound very similar to `copyto!`.

**Comment by pxl-th** [comment]
Scalar indexing no longer happens.
