### ISSUE TITLE
Optimize kernarg allocations in kernel construction

### ISSUE THREAD

**Issue by jpsamaroo** [JuliaGPU/AMDGPU.jl#247]
Aside from implementing memory pooling, the HSA documentation indicates that we can reuse kernarg allocations for multiple kernel launches when the arguments are the same (i.e. multiple kernels can read from the same kernarg segment concurrently). We should be able to reuse the existing caching infrastructure to determine when a kernarg segment can be shared across multiple kernel launches.

**Comment by luraess** [comment]
Would be cool to see if this helps to reduce the kernel launch times.
