### ISSUE TITLE
Implement occupancy API

### ISSUE THREAD

**Issue by torrance** [JuliaGPU/AMDGPU.jl#271]
CUDA has a great feature for sizing threads and blocks, namely launch_configuration(). I rarely manually size my kernel, instead something like:

```
kernel = @cuda launch=false myfunc(args...)
config = launch_configuration(kernel.fun)
threads = min(N, config.threads)
blocks = cld(N, threads)
kernel(args...; threads, blocks)
```

It’s almost always very close to optimal, and allows my code to move from device to device without worrying too much about launch parameters.

ROCM provides something similar in https://github.com/ROCm-Developer-Tools/hipamd/blob/3ec1ccdbbbee7090ba854eddd1dee281973a4498/src/hip_platform.cpp#L301

All array level kernels ultimately rely on GPUArray's `launch_configuration()`, which currently defaults to `threads=256, blocks=32`, and which is suboptimal. Enabling this functionality would improve all array-level programming.

This issue tracks the work required to port this function into AMDGPU.jl

**Comment by torrance** [comment]
To port this into AMDGPU, we need to know the used scalar and vector general purpose registers (SGPR, VGPR) for a given kernel.

These values seem to be provided by ROCclr in theWorkGroupInfo struct (https://github.com/ROCm-Developer-Tools/ROCclr/blob/dc5293c2ad63aec3b01d7636073f7cc86b02cc97/device/devkernel.hpp#L364) and the typical access pattern is:

    const device::Kernel::WorkGroupInfo* wrkGrpInfo = kernel.getDeviceKernel(device)->workGroupInfo();

The actual implementation here seems to be hidden, and I'm unsure how to query this information from Julia.

**Comment by jpsamaroo** [comment]
If you do something like `AMDGPU.@device_code_gcn wait(@roc identity(nothing))`, you'll see something like:

```
---
amdhsa.kernels:
  - .args:           []
    .group_segment_fixed_size: 0
    .kernarg_segment_align: 4
    .kernarg_segment_size: 0
    .language:       OpenCL C
    .language_version:
      - 2
      - 0
    .max_flat_workgroup_size: 1024
    .name:           _Z18julia_identity_829v
    .private_segment_fixed_size: 0
    .sgpr_count:     4
    .sgpr_spill_count: 0
    .symbol:         _Z18julia_identity_829v.kd
    .vgpr_count:     0
    .vgpr_spill_count: 0
    .wavefront_size: 64
amdhsa.version:
  - 1
  - 0
...
```

So with a little bit of parsing, we can extract this information.
