### ISSUE TITLE
Queue selection test fail

### ISSUE THREAD

**Issue by luraess** [JuliaGPU/AMDGPU.jl#274]
The queue priority selection tests currently fail (Julia 1.8, MI250x) with following error 
[queue_test_fail.txt](https://github.com/JuliaGPU/AMDGPU.jl/files/9437955/queue_test_fail.txt).

It seems that the following
https://github.com/JuliaGPU/AMDGPU.jl/blob/e0a48dd9aadc0329e176a983ff0d7ee0e824b252/test/hsa/queue.jl#L6
should rather be
```Julia
 ROCQueue(device; priority=priority)
```
However, after fixing this, one still gets the same error when running the test, while all works fine if the queue test file is executed from the REPL. Any thoughts?

ROCm v5.0.2 and
```
julia> AMDGPU.versioninfo()
HSA Runtime (ready)
- Path: /opt/rocm/lib/libhsa-runtime64.so.1
- Version: 1.1.0
ld.lld (ready)
- Path: /opt/rocm/llvm/bin/ld.lld
ROCm-Device-Libs (ready)
- Path: /opt/rocm/amdgcn/bitcode
- Downloaded: true
HIP Runtime (ready)
- Path: /opt/rocm/lib/libamdhip64.so.5
rocBLAS (ready)
- Path: /opt/rocm/lib/librocblas.so
rocSOLVER (ready)
- Path: /opt/rocm/lib/librocsolver.so
rocALUTION (ready)
- Path: /opt/rocm/lib/librocalution.so
rocSPARSE (ready)
- Path: /opt/rocm/lib/librocsparse.so
rocRAND (ready)
- Path: /opt/rocm/lib/librocrand.so
rocFFT (ready)
- Path: /opt/rocm/lib/librocfft.so
MIOpen (ready)
- Path: /opt/rocm/lib/libMIOpen.so
HSA Agents (5):
- CPU-XX [AMD EPYC 7A53 64-Core Processor]
- CPU-XX [AMD EPYC 7A53 64-Core Processor]
- CPU-XX [AMD EPYC 7A53 64-Core Processor]
- CPU-XX [AMD EPYC 7A53 64-Core Processor]
- GPU-315d196f433c7230 [gfx90a]
```

**Comment by jpsamaroo** [comment]
This is actually a data race, which #265 is intended to fix.

**Comment by luraess** [comment]
Oh yeah - I recall. This may fix the faulty behaviour but one should still need to fix the kwarg `ROCQueue(device; priority=priority)`, right?

**Comment by luraess** [comment]
Isn't the kwarg `priority=` still missing in #265 @jpsamaroo ?

**Comment by luraess** [comment]
No need for explicit keyword if LHS=RHS.
