### ISSUE TITLE
build failure on Julia 1.8.1

### ISSUE THREAD

**Issue by leios** [JuliaGPU/AMDGPU.jl#278]
I am not sure where to put this, but I'm getting a weird build error on Julia v1.8.1:

```
(@v1.8) pkg> build AMDGPU
    Building AMDGPU → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/ce65c7595ea396799eff73f471bae7750d11bb24/build.log`
ERROR: Error building `AMDGPU`: 
ERROR: LoadError: UndefVarError: is_available not defined
Stacktrace:
 [1] main()
   @ Main ~/.julia/packages/AMDGPU/iM314/deps/build.jl:291
 [2] top-level scope
   @ ~/.julia/packages/AMDGPU/iM314/deps/build.jl:439
 [3] include(fname::String)
   @ Base.MainInclude ./client.jl:476
 [4] top-level scope
   @ none:5
in expression starting at /home/leios/.julia/packages/AMDGPU/iM314/deps/build.jl:439
ROCm library search paths:
- /opt/rocm/lib
```
The line broken is:
```
if (Base.libllvm_version < v"14" && @invokelatest(LLD_jll.LLVM_jll.is_available())) || @invokelatest(LLD_jll.is_available())
```

So it might be an LLVM issue. I tried this on the master branch as well and ran into the same issue. I also rebuilt LLVM in v1.8.1 just in case that was the issue, but it also didn't seem to solve anything.

Note that julia v1.8.0 and other previous versions seem to work fine.

EDIT: I was just told that the build I am using from the arch repos might be causing this issue, so I guess the lesson is to avoid the arch repos for julia for now.

**Comment by jpsamaroo** [comment]
Closing as this isn't reproducible on release builds of Julia
