### ISSUE TITLE
Pause hostcall listeners when queues are quiet

### ISSUE THREAD

**Issue by jpsamaroo** [JuliaGPU/AMDGPU.jl#327]
Even when no kernels are executing, hostcall handlers can be listening in the background for activity. This apparently can generate quite a few allocations; executing a single `AMDGPU.ones` call can cause AMDGPU to begin allocating 25KB per second in the background, due to hostcall handlers.

As a temporary workaround, we should pause hostcall listeners whenever the queue they're servicing enters a quiescent state. We can also improve this situation by manually removing unnecessary allocations.

**Comment by pxl-th** [comment]
We now pause hostcalls once they are no longer needed: https://amdgpu.juliagpu.org/dev/hostcall/#Hostcall
