### ISSUE TITLE
sincospi intrinsic is broken

### ISSUE THREAD

**Issue by jpsamaroo** [JuliaGPU/AMDGPU.jl#334]
As reported by @torrance, because it returns two values. We should be able to support this, testing it will just require some manual handling.

**Comment by torrance** [comment]
I actually tried putting in a fix for this the other day, but I couldn't understand how to create a reference to a float/double on the stack to then pass into sincospi().

**Comment by jpsamaroo** [comment]
Oh, I had thought it returns a `Tuple{Float64,Float64}`, but looking at the LLVM IR I see that it takes `(Float64, Ptr{Float64})` and returns just a `Float64`. @torrance do you know where the API is documented? I can put together the necessary override for it once I know what goes where.

**Comment by jpsamaroo** [comment]
Nevermind, figured it out with some trial-and-error. I'll have a PR up soon!
