### ISSUE TITLE
Add function or macro for AMDGPU.jl equivalent to CUDA.CuDynamicSharedArray (and CUDA.CuStaticSharedArray)

### ISSUE THREAD

**Issue by omlins** [JuliaGPU/AMDGPU.jl#347]
@jpsamaroo It looks to me like you did already all the hard work for it, except for the final function or macro that would allow to directly allocate such memory  in one go.  See here:
https://github.com/JuliaGPU/AMDGPU.jl/pull/311#issuecomment-1284191562

**Comment by jpsamaroo** [comment]
This will probably have to be a set of macros.
