### ISSUE TITLE
Support for rand from Julia Base on device code

### ISSUE THREAD

**Issue by williamfgc** [JuliaGPU/AMDGPU.jl#378]
CUDA.jl has support for using functionality like `rand(Distributions.Uniform(-1, 1))` on kernel code, which AMDGPU.jl flags as invalid LLVM-IR.

What's the best way to add this kind of functionality? Happy to help.

**Comment by vchuravy** [comment]
Also needed by @utkarsh530 in https://github.com/SciML/DiffEqGPU.jl/pull/227

**Comment by jpsamaroo** [comment]
Probably in the short term we can copy-pasta most of CUDA.jl's implementation.
