### ISSUE TITLE
Make `unsafe_copy3d!` TLS compatible

### ISSUE THREAD

**Issue by luraess** [JuliaGPU/AMDGPU.jl#421]
Ideally, we want to extract the ROCSignal associated to a ROCQueue in order to sync or control execution flow of the async DMA copy function, which now uses `ROCSignal` for that, as in https://github.com/JuliaGPU/AMDGPU.jl/blob/919025a8f7c9de43c7cd16632722203875888cab/test/hsa/memory.jl#L31-L86

@jpsamaroo suggested that a possible way to achieve this is to allow these to be nothing: https://github.com/JuliaGPU/AMDGPU.jl/blob/919025a8f7c9de43c7cd16632722203875888cab/src/runtime/kernel-signal.jl#L16-L18
which one can then detect and we can detect and treat as a "naked" `ROCSignal`.

**Comment by pxl-th** [comment]
Current version is already TLS compatible
