### ISSUE TITLE
Cannot `unsafe_wrap` a device array if `lock=false`

### ISSUE THREAD

**Issue by Keluaa** [JuliaGPU/AMDGPU.jl#436]
Hello, I am trying to wrap a GPU array allocated from another library with a `ROCArray`:

```julia
julia> roc_array = Base.unsafe_wrap(ROCArray, pointer(my_array), size(my_array); lock=false)
ERROR: MethodError: no method matching AMDGPU.Runtime.Mem.Buffer(::Ptr{Float64}, ::Ptr{Nothing}, ::Ptr{Float64}, ::Int64, ::ROCDevice, ::Bool, ::Bool)

Closest candidates are:
  AMDGPU.Runtime.Mem.Buffer(::Ptr{Nothing}, ::Ptr{Nothing}, ::Ptr{Nothing}, ::Int64, ::ROCDevice, ::Bool, ::Bool)
   @ AMDGPU /home/briandl/.julia/packages/AMDGPU/ZRqNQ/src/runtime/memory.jl:27

Stacktrace:
 [1] unsafe_wrap(::Type{ROCArray}, ptr::Ptr{Float64}, dims::Tuple{Int64, Int64}; device::ROCDevice, lock::Bool)
   @ AMDGPU /home/briandl/.julia/packages/AMDGPU/ZRqNQ/src/array.jl:228
 [2] top-level scope
   @ REPL[19]:1
```

I pass `lock=false` to `unsafe_wrap` since `AMDGPU.Mem.lock` assumes that the pointer is a host pointer (if I understood the source code correctly).

[But at this line](https://github.com/JuliaGPU/AMDGPU.jl/blob/6028decb42643eb422d773d53ce6d6cd4a337b9c/src/array.jl#L227), if `lock=false`, `ptr` is not converted to a `Ptr{Cvoid}` as expected by `Mem.Buffer`, hence the bug.

**Comment by jpsamaroo** [comment]
Good find! That should be a one line fix, plus maybe a small test, if you wouldn't mind submitting a PR?
