### ISSUE TITLE
AMDGPU on windows

### ISSUE THREAD

**Issue by meysamrajabi95** [JuliaGPU/AMDGPU.jl#465]
Based on the new update of the ROCm driver: [https://rocm.docs.amd.com/en/latest/deploy/windows/quick_start.html]

now AMDGPU should work on Windows too, right?

**Comment by pxl-th** [comment]
In theory yes, but would require changes to AMDGPU.jl package.
Mainly (or at least) adapting to newer versions of LLVM (ROCm 5.5 uses LLVM 16) and taking into account Windows directory structure during initialization.

**Comment by pxl-th** [comment]
But Windows support is definitely on a list

**Comment by meysamrajabi95** [comment]
Thank you! So, I still can not use the AMDGPU package on Windows and I should wait for the new version of AMDGPU.jl ?
Because I set up ROCm and still got the "No GPU devices detected" error.

**Comment by pxl-th** [comment]
> Because I set up ROCm and still got the "No GPU devices detected" error.

Because it does not know about Windows directory structure and assumes Linux.
If you can adapt [`bindeps_setup`](https://github.com/JuliaGPU/AMDGPU.jl/blob/166a1f7e58dd02cd8cfd6d5dfa861cf1df38fd76/src/rocm_discovery.jl#L176) function that loads ROCm libraries to Windows that could be a start.

You'd need to change default paths (from `/opt/rocm` on Linux to whatever it is on Windows) and load `.dll` instead `.so`.

Also, I'm not sure about ROCm HSA library being available on Windows, which is one of the core libraries.

If you did everything correctly, `AMDGPU.versioninfo()` should give you paths to all libraries that it loaded:
```julia
julia> AMDGPU.versioninfo()
ROCm provided by: system
[+] HSA Runtime v1.1.0
    @ /opt/rocm-5.4.3/lib/libhsa-runtime64.so
[+] ld.lld
    @ /opt/rocm/llvm/bin/ld.lld
[+] ROCm-Device-Libs
    @ /opt/rocm/amdgcn/bitcode
[+] HIP Runtime v5.504.22804
    @ /opt/rocm-5.4.3/lib/libamdhip64.so
[+] rocBLAS v2.46.0
    @ /opt/rocm-5.4.3/lib/librocblas.so.0
[+] rocSOLVER v3.20.0
    @ /opt/rocm-5.4.3/lib/librocsolver.so
[+] rocALUTION
    @ /opt/rocm-5.4.3/lib/librocalution.so
[+] rocSPARSE
    @ /opt/rocm-5.4.3/lib/librocsparse.so
[+] rocRAND v2.10.5
    @ /opt/rocm-5.4.3/lib/librocrand.so
[+] rocFFT v1.0.21
    @ /opt/rocm-5.4.3/lib/librocfft.so
[+] MIOpen v2.19.0
    @ /opt/rocm-5.4.3/lib/libMIOpen.so

HIP Devices [1]
    1. HIPDevice(name="AMD Radeon RX 6700 XT", id=1)
```

**Comment by meysamrajabi95** [comment]
**now Im getting this:**
`julia> AMDGPU.versioninfo()
ROCm provided by: system
[-] HSA Runtime
[-] ld.lld
[-] ROCm-Device-Libs
[-] HIP Runtime
[-] rocBLAS
[-] rocSOLVER
[-] rocALUTION
[-] rocSPARSE
[-] rocRAND
[-] rocFFT
[-] MIOpen`

**but I believe I have all this lib in the ROCm driver installed path:**
![image](https://github.com/JuliaGPU/AMDGPU.jl/assets/117052792/2b678f25-c4bf-4e4d-a87d-d884e36cdff6)

**But I don't know how to add these to Julia/AMDGPU package so I don't have this error**

**Comment by pxl-th** [comment]
Is there a way to install dynamic libraries? `.lib` is a static library and won't work

**Comment by vchuravy** [comment]
I think those `.lib` are import libraries not static archives. The question is are there dll somewhere else?

Good news is that according to the LLVM docs the triple `amdhsa` is supported on windows if "AMD’s PAL runtime using the pal-amdhsa loader on Windows."

**Comment by vchuravy** [comment]
I just used wine to unpack the installer on Linux and as expected the `dll` are in the `bin` folder.

**Comment by pxl-th** [comment]
AMDGPU 0.8 has initial Windows support. Make sure to check [requirements](https://amdgpu.juliagpu.org/dev/#Installation).

**Comment by meysamrajabi95** [comment]
> AMDGPU 0.8 has initial Windows support. Make sure to check [requirements](https://amdgpu.juliagpu.org/dev/#Installation).

This is awesome. Thanks
