### ISSUE TITLE
Synchronization in REPL

### ISSUE THREAD

**Issue by michel2323** [JuliaGPU/AMDGPU.jl#500]
On Julia 1.9.3 with the latest `master` with system ROCm 5.4 the result of `a .+ b` is not synchronized in the REPL.

```julia
julia> using AMDGPU

julia> a = ROCVector(ones(2))
2-element ROCArray{Float64, 1, AMDGPU.Runtime.Mem.HIPBuffer}:
 1.0
 1.0

julia> b = ROCVector(ones(2))
2-element ROCArray{Float64, 1, AMDGPU.Runtime.Mem.HIPBuffer}:
 1.0
 1.0

julia> a .+ b
2-element ROCArray{Float64, 1, AMDGPU.Runtime.Mem.HIPBuffer}:
 -1.8325506472120096e-6
 -1.8325506472120096e-6

julia> @show a .+ b
a .+ b = [2.0, 2.0]
2-element ROCArray{Float64, 1, AMDGPU.Runtime.Mem.HIPBuffer}:
 2.0
 2.0
```

**Comment by luraess** [comment]
That may occur since the REPL may print after the kernel launch returned while computations were not finalised. One would need sync afterwards. This behaviour was already observed with earlier versions of Julia and AMDGPU.

**Comment by pxl-th** [comment]
#501 will fix this.
