### ISSUE TITLE
Update rocSPARSE to ROCm 6.0

### ISSUE THREAD

**Issue by pxl-th** [JuliaGPU/AMDGPU.jl#571]
@amontoison, just FYI, rocSPARSE requires update to work with ROCm 6.0+.
As an example, [rocsparse_spmv](https://rocm.docs.amd.com/projects/rocSPARSE/en/latest/generic.html#rocsparse-spmv) added new `stage` parameter which we need to pass.
For now, I'll disable tests for rocSPARSE if we are using ROCm 6.0+.

**Comment by amontoison** [comment]
@pxl-th I can update `rocSPARSE` if you regenerate the Julia wrappers (`librocsparse.jl`).
I can work on that this week. :smiley:

**Comment by pxl-th** [comment]
Replacing completely with a new wrapper would bump ROCm requirement to 6.0+.
If we want to support older versions, then we can select wrapper method depending on the HIP version at runtime.
I'll open a PR that does that and we can work from there.

**Comment by amontoison** [comment]
Is it not possible to create a file `librocsparse_deprecated.jl` that contains old wrappers that have been removed with ROCm 6.0?
It's what I did to support both CUDA 11 and CUDA 12 in CUDA.jl:
https://github.com/JuliaGPU/CUDA.jl/blob/master/lib/cusparse/libcusparse_deprecated.jl

After we could do something like this:
https://github.com/JuliaGPU/CUDA.jl/blob/master/lib/cusparse/interfaces.jl#L346

**Comment by pxl-th** [comment]
Oh yeah, I was doing something similar just without `_deprecated` separation :)
