### ISSUE TITLE
Distribute ROCR/ROCT via artifacts

### ISSUE THREAD

**Issue by jpsamaroo** [JuliaGPU/AMDGPU.jl#6]

**Comment by Micket** [comment]
I tried to get started with this (mostly learning how to use BinaryBuilder) https://github.com/JuliaPackaging/Yggdrasil/pull/1453

**Comment by gdkrmr** [comment]
Is this already working? I see a couple of merged PRs in JuliaPackaging.

**Comment by jpsamaroo** [comment]
Oh shoot I lost track of this! Thanks @Micket for getting those together and merged! I'll take the torch on making them build for musl libc and loading them in AMDGPU.jl.

**Comment by Micket** [comment]
Still something at least 3-4 additional packages i think (at least a AMD-GPU variant of LLVM, and then the ROCm device libs, and then some other stuff). AMD started releasing 3.7 versions fixing several build issues, but they didn't release it for all things simultaneously, so I never got around to the rest. I do have some drafts for the llvm and device libs stuff that I never opened a PR for.

**Comment by jpsamaroo** [comment]
Yeah that would include: llvm-project (AMD's fork), ROCm-CompilerSupport (comgr), ROCm-Device-Libs (we could start building them instead of downloading them from Ubuntu apt), and then eventually rocBLAS et. al. I think it's a great idea, and I've got builds of the first 3 working locally, so I can get those put up on Yggdrasil.

**Comment by 0x0f0f0f** [comment]
Building llvm is a pain, second only to building chromium. Is there any new progress on this? We might open an issue on the AMD ROCm repo to ask them to release a tarball of the binaries.

**Comment by Micket** [comment]
@0x0f0f0f I got distracted and never got around to finishing it https://github.com/JuliaPackaging/Yggdrasil/pull/1736
I forget what it got stuck on, and the old failed build logs are removed already it seems. Feel free to steal it and make a new working PR.

**Comment by 0x0f0f0f** [comment]
@Micket i think that building a custom LLVM fork for having arrays in the GPU is definitively overkill. Also, having to make an ubuntu chroot or unpacking .deb packages are terrible solutions. I'm opening an issue on AMD's ROCm repo to ask them to release a distro agnostic binary bundle.

**Comment by 0x0f0f0f** [comment]
https://github.com/RadeonOpenCompute/ROCm/issues/1295

**Comment by Micket** [comment]
Good luck, they already have something like 3 LLVM forks :)

**Comment by 0x0f0f0f** [comment]
I managed to make it everything run in an Ubuntu chroot. It is probably what i am going to use by now.

**Comment by jpsamaroo** [comment]
The point of the extra LLVM is that it's a static library (.a instead of .so), so we don't need to link against it at runtime. This avoids some of the issues with having two different libLLVMs loaded into the same program at once. Packaging a binary bundle with all the ROCm stuff won't fix that, because as @Micket pointed out, AMD builds against their own LLVM, which doesn't have Julia's patches and will necessarily conflict with Julia's LLVM.

**Comment by jpsamaroo** [comment]
Further artifacts (HIP, rocBLAS, rocFFT, etc.) will be making their way into JLLs in the next few days, if all goes well!
