### ISSUE TITLE
GPUCompiler.CodeCache not defined

### ISSUE THREAD

**Issue by hearnsj** [JuliaGPU/AMDGPU.jl#632]
On a system with ROCm 6.1.0 I fail to install AMDGPU.jl
The error is certainly at my end, and I am investigating.

julia> versioninfo()
Julia Version 1.11.0-beta1
Commit 08e1fc0abb9 (2024-04-10 08:40 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × AMD EPYC 7313 16-Core Processor
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, znver3)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
Environment:
  LD_RUN_PATH = /shared/apps/ubuntu/opt/rocm-6.1.0/lib:/shared/apps/ubuntu/opt/rocm-6.1.0/hip/lib:/shared/apps/ubuntu/opt/rocm-6.1.0/hsa/lib:/shared/apps/ubuntu/opt/rocm-6.1.0/lib64:/shared/apps/ubuntu/opt/rocm-6.1.0/opencl/lib:/shared/apps/ubuntu/opt/rocm-6.1.0/opencl/lib/x86_64:/shared/apps/ubuntu/opt/rocm-6.1.0/llvm/lib
  LD_LIBRARY_PATH = /shared/apps/ubuntu/opt/rocm-6.1.0/lib:/shared/apps/ubuntu/opt/rocm-6.1.0/hip/lib:/shared/apps/ubuntu/opt/rocm-6.1.0/hsa/lib:/shared/apps/ubuntu/opt/rocm-6.1.0/lib64:/shared/apps/ubuntu/opt/rocm-6.1.0/opencl/lib:/shared/apps/ubuntu/opt/rocm-6.1.0/opencl/lib/x86_64:/shared/apps/ubuntu/opt/rocm-6.1.0/llvm/lib

Failed to precompile AMDGPU [21141c5a-9bdb-4563-92ae-f87d6854732e] to "/shared/prod/home/hearnsj/.julia/compiled/v1.11/AMDGPU/jl_X1veTj".
ERROR: LoadError: UndefVarError: `CodeCache` not defined in `GPUCompiler`
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base ./Base.jl:42
 [2] top-level scope
   @ ~/.julia/packages/AMDGPU/gtxsf/src/AMDGPU.jl:75
 [3] include
   @ ./Base.jl:558 [inlined]
 [4] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
   @ Base ./loading.jl:2721
 [5] top-level scope
   @ stdin:4
in expression starting at /shared/prod/home/hearnsj/.julia/packages/AMDGPU/gtxsf/src/AMDGPU.jl:1
in expression starting at stdin:

**Comment by vchuravy** [comment]
Likely AMD GPU needs to be updated for 1.11

**Comment by hearnsj** [comment]
I will have time to investigate further tomorrow (UK time)

**Comment by pxl-th** [comment]
I plan to work on 1.11 support soon. I'm finishing reworking a bit how memory buffers are handled and after that I'll focus on 1.11
