### ISSUE TITLE
Unable to find correct HIP path

### ISSUE THREAD

**Issue by eirikfagerbakke** [JuliaGPU/AMDGPU.jl#671]
Hi!
I am kind of a noob when it comes to GPU programming, so apologies if this is a trivial question.
When calling `AMDGPU.versioninfo()`, the path listed for HIP is `"C:\\WINDOWS\\SYSTEM32\\amdhip64.DLL"`. This is however an old version, and I think the correct version should be `"C:\\Program Files\\AMD\\ROCm\\6.1\\bin\\amdhip64_6.DLL"`. I have tried deleting the old `amdhip64.dll` file, but then AMDGPU isn't able to build. Everything else seems to find the correct path.
I also do not have MIOpen, but from what I can understand, this is only available on Linux. Is this a big problem?
I am specifically going to be using AMDGPU with Lux.jl.

Is there any way I can manually change the HIP path? Or should I finally just switch over to Linux?
Any help would be greatly appreciated.

**Comment by pxl-th** [comment]
We probably need to change this line to account for the change in name (`amdhip64_6`): https://github.com/JuliaGPU/AMDGPU.jl/blob/7bec32ccc74b0b0d2502e0473c566b40a8d7ace4/src/discovery/discovery.jl#L137

MIOpen is used for convolutions so it you need them, then it is probably better to swtich to Linux :)

**Comment by eirikfagerbakke** [comment]
> We probably need to change this line to account for the change in name (`amdhip64_6`):
> 
> https://github.com/JuliaGPU/AMDGPU.jl/blob/7bec32ccc74b0b0d2502e0473c566b40a8d7ace4/src/discovery/discovery.jl#L137

I tried changing it just now, but I now get the error `ERROR: InitError: HIPError(code hipErrorNoDevice, no device found)` after re-building and simply running `using AMDGPU`. I also tried just naively changing the file name to "amdhip64", but then I got errors from the other ROCm files.

> MIOpen is used for convolutions so it you need them, then it is probably better to swtich to Linux :)

Aa okay, good to know! I think I might give Linux a try then :)
